#!/bin/bash
set -e

GREEN='\033[0;32m'
RED='\033[0;31m'
NC='\033[0m'

commonSetups(){
  printf "${GREEN}*** Deploying all contracts ***${NC}\n"
  docker-compose run --rm truffle-offchain migrate --reset --network=default
  docker-compose run --rm truffle-zkp migrate --reset --network=default

  printf "${GREEN}*** Launching RabbitMQ container ***${NC}\n"
  docker-compose up -d rabbitmq

  sleep 3
}

printf "${GREEN}*** Cleaning up all containers ***${NC}\n"
docker-compose down -v || {
	# this block will run if ```docker-compose down -v``` fails.
	sleep 3

	printf "${GREEN}*** Remove nightfall network ***${NC}\n"
  docker network rm nightfall_network

  printf "${GREEN}*** Remove nightfall's mongo volume ***${NC}\n"
  docker volume rm nightfall_mongo-nightfall-volume

  printf "${GREEN}*** Remove zkp-code volume ***${NC}\n"
  docker volume rm nightfall_zkp-code-volume

	printf "${GREEN}*** Remove merkle_tree network ***${NC}\n"
  docker network rm merkle_tree_network

	printf "${GREEN}*** Remove the merkle tree's mongo volume ***${NC}\n"
  docker volume rm nightfall_mongo-merkle-tree-volume
}

printf  "${GREEN}*** Delete zkp and offchain contract's build folder ***${NC}\n"
rm -dr zkp/build/ || true
rm -dr offchain/build/ || true

printf "${GREEN}*** Delete zkp/contracts/MerkleTree.sol created by MiMC hash run ***${NC}\n"
rm zkp/contracts/MerkleTree.sol || true

printf "${GREEN}*** Pull zokrates docker image ***${NC}\n"
docker pull zokrates/zokrates:0.5.1

printf "${GREEN}*** docker-compose Build ***${NC}\n"
docker-compose build

printf "${GREEN}*** Installing zkp-util dependencies"
pushd zkp-utils
npm ci
popd

if [[ "$1" == "compliance" ]]
then
	printf "${RED}Using the compliance extensions${NC}\n"

  printf "${GREEN}*** Launching containerized ganache ***${NC}\n"
	docker-compose -f docker-compose.yml -f docker-compose.override.compliance.yml up -d ganache

  commonSetups

  printf "${GREEN}*** Launching containerized microservices ***${NC}\n"
  docker-compose -f docker-compose.yml -f docker-compose.override.compliance.yml up

elif [[ -f ./zkp/code/gm17/ft-consolidation-transfer/proving.key && -f ./zkp/code/gm17/ft-consolidation-transfer/verification.key  ]]
then
  printf "${GREEN}*** Launching containerized ganache ***${NC}\n"
  docker-compose up -d ganache

  commonSetups

  printf "${GREEN}*** Launching containerized microservices ***${NC}\n"
  docker-compose -f docker-compose.yml -f docker-compose.override.mimc.yml up

else
	printf "${GREEN}*** docker-compose Build ***${NC}\n"
  docker-compose build

  printf "${GREEN}*** Launching containerized ganache ***${NC}\n"
  docker-compose up -d ganache

  commonSetups

  printf "${GREEN}*** Launching containerized microservices ***${NC}\n"
  docker-compose up
fi
