name: Run Nightfall test suite

on:
  pull_request:
    branches:
      - master

jobs:
  eslint-test:
    name: Run eslint check
    runs-on: ubuntu-18.04
    env:
      NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '14.15.0'
      - name: run npm install in all microservices
        run: |
          npm ci
          cd accounts/ && npm ci && cd ..
          cd api-gateway/ && npm ci && cd ..
          cd database/ && npm ci && cd ..
          cd offchain/ && npm ci && cd ..
          cd zkp/ && npm i && cd ..
      - name: Run check for ESLint errors
        run: npm run lint

  zkp-unit-test-sha:
    name: ZKP microservice unit test (HASH_TYPE = sha)
    runs-on: ubuntu-18.04
    env:
      NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '14.15.0'
      - name: Pull docker image
        run: |
          docker rmi $(docker images -aq)
          docker pull zokrates/zokrates:0.5.1
      - name: Increase swap memory
        run: |
          sudo usermod -a -G sudo runner
          sudo swapoff -a
          sudo fallocate -l 12G /mnt/swapfile
          sudo mkswap /mnt/swapfile
          sudo swapon /mnt/swapfile
      - name: Build docker images
        run: docker-compose build --build-arg NPM_TOKEN=${NPM_TOKEN} truffle-zkp truffle-nightlite zkp
      - name: Generate the keys and constraint files for Zero Knowledge Proofs
        run: |
          chmod -R 777 zkp/code/
          npm run setupAll
      - name: Remove containers
        run: docker-compose down -v
      - name: Move ft-batch-transfer to make space
        run: |
          sudo mv zkp/code/gm17/ft-batch-transfer /dev/ft-batch-transfer
          sudo ln -s /dev/ft-batch-transfer zkp/code/gm17/ft-batch-transfer
          df -h
      - name: Deploy zkp contracts
        run: |
          docker-compose run --rm truffle-zkp compile --all
          docker-compose run --rm truffle-zkp migrate --reset --network=default
      - name: Deploy Nightlite contracts
        run: |
          cd zkp/ && npm i && cd ..
          docker-compose run --rm truffle-nightlite compile --all
          docker-compose run --rm truffle-nightlite migrate --reset --network=default
      - name: Run zkp unit tests
        run: docker-compose run --rm zkp npm test

  zkp-unit-test-mimc:
    name: ZKP microservice unit test (HASH_TYPE = mimc)
    runs-on: ubuntu-18.04
    env:
      NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '14.15.0'
      - name: Pull docker image
        run: |
          docker rmi $(docker images -aq)
          docker pull zokrates/zokrates:0.5.1
      - name: Increase swap memory
        run: |
          sudo usermod -a -G sudo runner
          sudo swapoff -a
          sudo fallocate -l 13G /mnt/swapfile
          sudo mkswap /mnt/swapfile
          sudo swapon /mnt/swapfile
      - name: Rename mimc docker-compose yml file
        run: mv docker-compose.override.mimc.yml docker-compose.override.yml
      - name: Build docker images
        run: docker-compose build --build-arg NPM_TOKEN=${NPM_TOKEN} truffle-zkp truffle-nightlite zkp
      - name: Generate the keys and constraint files for Zero Knowledge Proofs
        run: |
          chmod -R 777 zkp/code/
          npm run setupAll-mimc
      - name: Remove containers
        run: docker-compose down -v
      - name: Move ft-batch-transfer to make space
        run: |
          sudo mv zkp/code/gm17/ft-batch-transfer /dev/ft-batch-transfer
          sudo ln -s /dev/ft-batch-transfer zkp/code/gm17/ft-batch-transfer
          df -h
      - name: Deploy zkp contracts
        run: |
          docker-compose run --rm truffle-zkp compile --all
          docker-compose run --rm truffle-zkp migrate --reset --network=default
      - name: Deploy Nightlite contracts
        run: |
          cd zkp/ && npm i && cd ..
          docker-compose run --rm truffle-nightlite compile --all
          docker-compose run --rm truffle-nightlite migrate --reset --network=default
      - name: Run zkp unit tests
        run: docker-compose run --rm zkp npm test

  zkp-unit-test-compliance:
    name: ZKP microservice unit test for compliance setup
    runs-on: ubuntu-18.04
    env:
      NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '14.15.0'
      - name: Pull docker image
        run: |
          docker rmi $(docker images -aq)
          docker pull zokrates/zokrates:0.5.1
      - name: Increase swap memory
        run: |
          sudo usermod -a -G sudo runner
          sudo swapoff -a
          sudo fallocate -l 13G /mnt/swapfile
          sudo mkswap /mnt/swapfile
          sudo swapon /mnt/swapfile
      - name: Rename compliance docker-compose yml file
        run: mv docker-compose.override.compliance.yml docker-compose.override.yml
      - name: Build docker images
        run: docker-compose build --build-arg NPM_TOKEN=${NPM_TOKEN} truffle-zkp truffle-nightlite zkp
      - name: Generate the keys and constraint files for Zero Knowledge Proofs
        run: |
          chmod -R 777 zkp/code/
          npm run setupAll-rc
      - name: Remove containers
        run: docker-compose down -v
      - name: Deploy zkp contracts
        run: |
          docker-compose run --rm truffle-zkp compile --all
          docker-compose run --rm truffle-zkp migrate --reset --network=default
      - name: Deploy Nightlite contracts
        run: |
          cd zkp/ && npm i && cd ..
          docker-compose run --rm truffle-nightlite compile --all
          docker-compose run --rm truffle-nightlite migrate --reset --network=default
      - name: Run zkp unit tests
        run: docker-compose run --rm zkp npm test

  integration-test-sha:
    name: Run integration test (HASH_TYPE = sha)
    runs-on: ubuntu-18.04
    env:
      NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_ACTION: 'true'
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '14.15.0'
      - name: Pull docker image
        run: |
          docker rmi $(docker images -aq)
          docker pull zokrates/zokrates:0.5.1
      - name: Increase swap memory
        run: |
          sudo usermod -a -G sudo runner
          sudo swapoff -a
          sudo fallocate -l 12G /mnt/swapfile
          sudo mkswap /mnt/swapfile
          sudo swapon /mnt/swapfile
      - name: Build docker images
        run: docker-compose build --build-arg NPM_TOKEN=${NPM_TOKEN}
      - name: Generate the keys and constraint files for Zero Knowledge Proofs
        run: |
          chmod -R 777 zkp/code/
          npm run setupAll
      - name: Remove containers
        run: docker-compose down -v
      - name: Move ft-batch-transfer to make space
        run: |
          sudo mv zkp/code/gm17/ft-batch-transfer /dev/ft-batch-transfer
          sudo ln -s /dev/ft-batch-transfer zkp/code/gm17/ft-batch-transfer
          df -h
      - name: Run integration test
        run: ./nightfall-test
      - name: If integration test failed, upload logs files as artifacts
        if: failure()
        uses: actions/upload-artifact@master
        with:
          name: integration-test-logs
          path: nightfall_test.log

  integration-test-mimc:
    name: Run integration test (HASH_TYPE = mimc)
    runs-on: ubuntu-18.04
    env:
      NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_ACTION: 'true'
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '14.15.0'
      - name: Pull docker image
        run: |
          docker rmi $(docker images -aq)
          docker pull zokrates/zokrates:0.5.1
      - name: Increase swap memory
        run: |
          sudo usermod -a -G sudo runner
          sudo swapoff -a
          sudo fallocate -l 13G /mnt/swapfile
          sudo mkswap /mnt/swapfile
          sudo swapon /mnt/swapfile
      - name: Rename mimc docker-compose yml file
        run: cp docker-compose.override.mimc.yml docker-compose.override.yml
      - name: Build docker images
        run: docker-compose build --build-arg NPM_TOKEN=${NPM_TOKEN}
      - name: Generate the keys and constraint files for Zero Knowledge Proofs
        run: |
          chmod -R 777 zkp/code/
          npm run setupAll-mimc
      - name: Remove containers
        run: docker-compose down -v
      - name: Move ft-batch-transfer to make space
        run: |
          sudo mv zkp/code/gm17/ft-batch-transfer /dev/ft-batch-transfer
          sudo ln -s /dev/ft-batch-transfer zkp/code/gm17/ft-batch-transfer
          df -h
      - name: Run integration test
        run: ./nightfall-test mimc
      - name: If integration test failed, upload logs files as artifacts
        if: failure()
        uses: actions/upload-artifact@master
        with:
          name: integration-test-logs
          path: nightfall_test.log

  integration-test-compliance:
    name: Run compliance integration test
    runs-on: ubuntu-18.04
    env:
      NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_ACTION: 'true'
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '14.15.0'
      - name: Pull docker image
        run: |
          docker rmi $(docker images -aq)
          docker pull zokrates/zokrates:0.5.1
      - name: Increase swap memory
        run: |
          sudo usermod -a -G sudo runner
          sudo swapoff -a
          sudo fallocate -l 13G /mnt/swapfile
          sudo mkswap /mnt/swapfile
          sudo swapon /mnt/swapfile
      - name: Rename compliance docker-compose yml file
        run: cp docker-compose.override.compliance.yml docker-compose.override.yml
      - name: Build docker images
        run: docker-compose build --build-arg NPM_TOKEN=${NPM_TOKEN}
      - name: Generate the keys and constraint files for Zero Knowledge Proofs
        run: |
          chmod -R 777 zkp/code/
          npm run setupAll-rc
      - name: Remove containers
        run: docker-compose down -v
      - name: Run integration test
        run: ./nightfall-test compliance
      - name: If integration test failed, upload logs files as artifacts
        if: failure()
        uses: actions/upload-artifact@master
        with:
          name: integration-test-logs
          path: nightfall_test.log
